# Spring Configuration
spring:
    application:
        name: ong

    datasource:
        url: jdbc:h2:mem:db
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        hibernate:
          ddl-auto: create
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
    h2:
      console:
        enabled: true
        path: /h2
        settings:
          trace: false
          web-allow-others: false

# SpringDOC
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger


# Logging Configuration
logging:
  level:
    org:
        hibernate:
            SQL: DEBUG
            type:
                descriptor:
                    sql:
                    BasicBinder: TRACE
        springframework: DEBUG

server:
  port: 8081