@startuml
node "Servidor local" {
    component "Controller" {
        [UsuarioController] 
        [ClienteController]
        [AgenteController]
        [AluguelController]
        [AutenticacaoController]
    }

    component "Service" {
        [UsuarioService] 
        [ClienteService]
        [AgenteService]
        [AluguelService]
        [AutenticacaoService]
    }

    component "Repository" {
        [UsuarioRepository]
        [ClienteRepository]
        [AgenteRepository]
        [AluguelRepository]
    }


    database "Banco de Dados H2" {
        [H2Database]
    }
}

node "Banco" {
}

node "Agentes Locais" {
}

node "Locatário" {
}

interface "Requisiçao de aluguel" as RAL

RAL  - [Locatário]

"Locatário" --> AluguelController
"Locatário" --> ClienteController
"Locatário" --> AutenticacaoController

"Banco" --> AluguelController
"Banco" --> AutenticacaoController

"Agentes Locais" --> UsuarioController
"Agentes Locais" --> ClienteController
"Agentes Locais" --> AgenteController
"Agentes Locais" --> AluguelController
"Agentes Locais" --> AutenticacaoController

UsuarioController --> UsuarioService
ClienteController --> ClienteService
AgenteController --> AgenteService
AluguelController --> AluguelService
AutenticacaoController --> AutenticacaoService

UsuarioService --> UsuarioRepository
ClienteService --> ClienteRepository
AgenteService --> AgenteRepository
AluguelService --> AluguelRepository

UsuarioRepository --> H2Database
ClienteRepository --> H2Database
AgenteRepository --> H2Database
AluguelRepository --> H2Database
@enduml
