@startuml
node "Servidor local" {
    component "Controller" {
        [UsuarioController] 
        [ClienteController]
        [AgenteController]
        [AluguelController]
    }

    component "Service" {
        [UsuarioService] 
        [ClienteService]
        [AgenteService]
        [AluguelService]
    }

    component "Repository" {
        [UsuarioRepository]
        [ClienteRepository]
        [AgenteRepository]
        [AluguelRepository]
    }


    database "Banco de Dados H2" {
        [H2Database]
    }
}

node "Agentes Externos" {
    [API Rest/HTTP Client]
}

node "Clientes Locais" {
    [CLI (Interface de Linha de Comando)]
}

"Agentes Externos" --> UsuarioController
"Agentes Externos" --> ClienteController
"Agentes Externos" --> AgenteController
"Agentes Externos" --> AluguelController

"Clientes Locais" --> UsuarioController
"Clientes Locais" --> ClienteController
"Clientes Locais" --> AgenteController
"Clientes Locais" --> AluguelController

UsuarioController --> UsuarioService
ClienteController --> ClienteService
AgenteController --> AgenteService
AluguelController --> AluguelService

UsuarioService --> UsuarioRepository
ClienteService --> ClienteRepository
AgenteService --> AgenteRepository
AluguelService --> AluguelRepository

UsuarioRepository --> H2Database
ClienteRepository --> H2Database
AgenteRepository --> H2Database
AluguelRepository --> H2Database
@enduml
