@startuml
abstract class Usuario {
    -Long id
    -String nome
    -String cpf
    -String rg
    -String email
}

class Cliente {
    -Date dataNascimento
    -Endereco endereco
    -String ocupacao
    -List<Renda> rendas
}

class Renda {
    -String empregador
    -double valor
    -LocalDate dataRecebimento
}

class Endereco {
    -Long id
    -String rua
    -String numero
    -String complemento
    -String bairro
    -String cidade
    -String estado
    -String cep
}

'matrícula, ano, marca, modelo e placa.
class Veiculo {
    -Long id
    -TipoVeiculo tipoVeiculo
    -String modelo
    -int ano
    -String cor
    -String placa
    -double quilometragem
    -StatusVeiculo status    
}

Enum TipoVeiculo {
    CARRO
    MOTO
    CAMINHAO
    VAN
    ONIBUS
    SUV
    CONVERSIVEL
    PICKUP
}

Enum StatusVeiculo {
    DISPONIVEL
    INDISPONIVEL
    ALUGADO
}

class Aluguel {
    -Long id
    -Carro carro
    -Cliente cliente
    -LocalDate dataAluguel
    -LocalDate dataDevolucao
    -double taxaDiaria
    -Seguro seguro
    -double valorTotal
    -StatusAluguel status = Status.Pendente
    -bool desejaAdiquirirVeiculo
}

Enum StatusFinanceiro {
    PENDENTE
    APROVADO
    NEGADO
}

Enum StatusAluguel {
    APROVADO
    NEGADO
    ATIVO
    CONCLUIDO
    CANCELADO
    PENDENTE
    ATRASADO
}

class Agencia {
    -Long id
    -String nome
    -Endereco endereco
    -List<Veiculo> veiculos
    -List<Aluguel> alugueis

'    +listarVeiculosDisponiveis()
'    +alugarVeiculo()
'    +receberVeiculo()
'    +atualizarFatura()
'    +obterAlugueisCliente(Cliente cliente)
'    +buscarVeiculoPorPlaca(String placa)
'    +obterAlugueisAtrasados()
}

class Fatura {
    -Long id
    -Cliente cliente
    -Aluguel aluguel
    -Double imposto
    -Double taxas
}

class Financeiro {
'    -verificarAlugueisPendentes()
'    -verificarAlugueisAprovados()
'    -verificarAlugueisNegados()
'    -aprovarAluguel()
'    -negarAluguel()
}

class Contrato{
    -Cliente cliente
    -Agente agenteLocador
    -Agente agenteFinanceiro
    -Date dataInicio
    -Date dataTermino
    -Veiculo veiculoLocado
    -TipoContrato tipoContrato
    -StatusFinanceiro statusFinanceiro
}

Enum TipoContrato{
    12_MESES
    24_MESES
    36_MESES
    48_MESES
}


class Seguro {
    -Long id
    -String nome
    -Veiculo veiculoModelo
    -double valorDiario
    -double taxas
}

Cliente o-- Endereco
Cliente o-- Renda
Aluguel o-- Veiculo
Aluguel o-- Cliente
Aluguel o-- Seguro
Agencia o-- Endereco
Agencia o-- Veiculo
Agencia o-- Aluguel
Fatura o-- Cliente
Fatura o-- Aluguel
Financeiro o-- Funcionario
Seguro o-- Veiculo

Usuario <|-- Funcionario
Usuario <|-- Cliente

TipoVeiculo <|-- Veiculo
StatusVeiculo <|-- Veiculo
StatusFinanceiro <|-- Aluguel
StatusAluguel <|-- Aluguel
@enduml
