@startuml Diagrama
package "Gestão de Usuários" {
    abstract class Usuario

    class Cliente

    class Agente

    class FuncionarioEmpresa

    class FuncionarioBanco

    class Rendimento

    enum TipoUsuario {
        CLIENTE
        AGENTE
        FUNCIONARIO_BANCO
    }
}

package "Gestão de Aluguel" {
    class Aluguel

    class Automovel

    enum StatusAutomovel {
        DISPONIVEL
        ALUGADO
    }

    enum PrazoAluguel {
        M12
        M24
        M36
        M48
    }

    enum StatusPedido {
        PENDENTE
        APROVADO
        REPROVADO
        CANCELADO
        EXECUTADO
    }
}

package "Gestão de Contratos" {
    class ContratoAluguel

    class Credito

    enum StatusContrato {
        ATIVO
        INATIVO
    }
}

package "Controladores" {
    class AluguelController

    class UsuarioController

    class ContratoAluguelController

    class CreditoController
}

' Relações entre as classes de Modelo
Usuario <|-- Cliente
Usuario <|-- Agente
Agente <|-- FuncionarioEmpresa
Agente <|-- FuncionarioBanco
Cliente "1" -- "0..3" Rendimento
Cliente -- Aluguel
Aluguel -- Automovel
Aluguel -- ContratoAluguel
ContratoAluguel -- Credito
FuncionarioBanco "1" -- "*" Credito
' Relações entre Controladores e Classes de Modelo
AluguelController -- Aluguel
AluguelController -- Cliente
UsuarioController -- Usuario
ContratoAluguelController -- ContratoAluguel
CreditoController -- Credito

@enduml
