@startuml Diagrama de Casos de Uso
left to right direction

actor "Usuário" as usuario
actor "Cliente" as cliente
actor "Funcionário da empresa" as empresa
actor "Funcionário do banco" as banco

rectangle "Sistema de aluguel de carros" {
    usecase "Realizar cadastro" as uc_cadastro
    usecase "Criar pedido de aluguel" as uc_criar_pedido
    usecase "Modificar pedido de aluguel" as uc_modificar_pedido
    usecase "Cancelar pedido de aluguel" as uc_cancelar_pedido
    usecase "Consultar pedido de aluguel" as uc_consultar_pedido
    usecase "Avaliar pedido de aluguel" as uc_avaliar_pedido
    usecase "Executar contrato de aluguel" as uc_executar_contrato
    usecase "Conceder crédito" as uc_conceder_credito
}

usuario <|-- cliente
usuario <|-- empresa
empresa <|-- banco

usuario -- uc_cadastro

cliente -- uc_criar_pedido
cliente -- uc_modificar_pedido
cliente -- uc_consultar_pedido
cliente -- uc_cancelar_pedido
cliente -- uc_executar_contrato

empresa -- uc_avaliar_pedido

banco -- uc_conceder_credito

uc_executar_contrato ..> uc_avaliar_pedido : "<<include>>"
uc_avaliar_pedido ..> uc_criar_pedido : "<<include>>"
uc_conceder_credito ..> uc_avaliar_pedido : "<<include>>"
uc_modificar_pedido ..> uc_cadastro : "<<include>>"
uc_cancelar_pedido ..> uc_cadastro : "<<include>>"
uc_consultar_pedido ..> uc_cadastro : "<<include>>"
uc_criar_pedido ..> uc_cadastro : "<<include>>"

uc_modificar_pedido ..> uc_criar_pedido : "<<extend>>"
uc_cancelar_pedido ..> uc_criar_pedido : "<<extend>>"
uc_conceder_credito ..> uc_executar_contrato : "<<extend>>"
@enduml
