@startuml DiagramaDeClasses
left to right direction

enum StatusPedido {
    PENDENTE
    APROVADO
    REPROVADO
    CANCELADO
    EXECUTADO
}

enum StatusContrato {
    ATIVO
    INATIVO
}

enum TipoUsuario {
    CLIENTE
    AGENTE
    FUNCIONARIO_BANCO
}

class Usuario {
    - id: int
    - tipo: TipoUsuario
    - nome: String
    - email: String
    - senha: String

    + logar(email: String, senha: String): boolean
}

class Cliente {
    - rg: String
    - cpf: String
    - profissao: String
    - endereco: Endereco

    - rendimentos: List<Cargos>
}

class Agente {
}

class FuncionarioBanco {
    nomeBanco: String
}

class Cargos {
    - id: int
    - nome: String
    - cnpj: String
    - atual: boolean
    - renda: double
    - dataInicio: Date
    - dataFim: Date
}

class Endereco {
    - id: int
    - rua: String
    - numero: int
    - bairro: String
    - cidade: String
    - estado: String
    - cep: String
}

class PedidoAluguel {
    - id: int
    - dataCriacao: Date
    - status: StatusPedido
    - valor: double
    - contrato: ContratoAluguel
}

class ContratoAluguel {
    - id: int
    - dataInicio: Date
    - dataFim: Date
    - duracao: int
    - valor: double
    - status: StatusContrato
    - credito: Credito
}

class Automovel {
    - id: int
    - matricula: String
    - ano: int
    - marca: String
    - modelo: String
    - placa: String
}

class Credito {
    - id: int
    - valor: double
    - taxaJuros: double
    - condedente: FuncionarioBanco
}

Usuario <|-- Cliente
Usuario <|-- Agente
Usuario <|-- FuncionarioBanco

Cliente -- PedidoAluguel : solicita >

Agente "1" -- "*" PedidoAluguel : avalia >

FuncionarioBanco -- Credito : concede >

PedidoAluguel "1" -- "1" Automovel : aluga >
PedidoAluguel "1" -- "1" Credito : associado a >

ContratoAluguel "1" -- "1" PedidoAluguel : refere-se a >
ContratoAluguel "1" -- "1" Automovel : utiliza >

Credito "1" ..> "1" ContratoAluguel : associado a >

Cliente "1" -- "0..3" Cargos : possui >

Cliente "1" -- "1" Endereco : reside em >

StatusPedido -- PedidoAluguel
StatusContrato -- ContratoAluguel
TipoUsuario -- Usuario

@enduml