@startuml    
    package "Controllers" {
        class AluguelController
        class UsuarioController
        class ContratoController
        class AutomovelController
        class PagamentoController
    }

    package "DTOs" {
        class AluguelDTO
        class UsuarioDTO
        class ContratoDTO
        class AutomovelDTO
        class PagamentoDTO
    }

    package "Services" {
        class AluguelService
        class UsuarioService
        class ContratoService
        class AutomovelService
        class PagamentoService
    }

    package "Mappers" {
        class AluguelMapper
        class UsuarioMapper
        class ContratoMapper
        class AutomovelMapper
        class PagamentoMapper
    }

    package "Repositories" {
        class AluguelRepository
        class UsuarioRepository
        class ContratoRepository
        class AutomovelRepository
        class PagamentoRepository
    }

    package "Entities" {
        abstract class Usuario {
        }
        class Cliente
        class Agente
        class FuncionarioEmpresa
        class FuncionarioBanco
        class Aluguel
        class Automovel
        class ContratoAluguel
        class Pagamento
        class Credito
        class Rendimento
        class TipoUsuario {
            <<enumeration>>
            CLIENTE
            AGENTE
            FUNCIONARIO_BANCO
        }
        enum StatusAutomovel {
            DISPONIVEL
            ALUGADO
        }
        enum PrazoAluguel {
            M12
            M24
            M36
            M48
        }
        enum StatusPedido {
            PENDENTE
            APROVADO
            REPROVADO
            CANCELADO
            EXECUTADO
        }
        enum StatusContrato {
            ATIVO
            INATIVO
        }
    }

    Controllers ..> DTOs
    Controllers ..> Services
    Services ..> Repositories
    Services ..> Mappers
    Mappers ..> DTOs
    Mappers ..> Entities
    Repositories ..> Entities

    Usuario <|-- Cliente
    Usuario <|-- Agente
    Agente <|-- FuncionarioEmpresa
    Agente <|-- FuncionarioBanco
    Usuario --> TipoUsuario
    Cliente "1" -- "0..3" Rendimento
    Cliente -- Aluguel
    Agente -- Aluguel
    Aluguel -- Automovel
    Aluguel -- ContratoAluguel
    ContratoAluguel -- Credito
    ContratoAluguel -- Pagamento
    FuncionarioBanco "1" -- "*" Credito
    Automovel --> StatusAutomovel
    Aluguel --> PrazoAluguel
    Aluguel --> StatusPedido
    ContratoAluguel --> StatusContrato
